/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inmobiliaria_mddp.vistas;

/**
 *
 * @author marti
 */
public class GestionCalquileres extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestionCalquileres
     */
    public GestionCalquileres() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_tituloCalquis = new javax.swing.JLabel();
        jB_buscar = new javax.swing.JButton();
        jL_codigo = new javax.swing.JLabel();
        jTF_codigo_ID = new javax.swing.JTextField();
        jL_inquilino = new javax.swing.JLabel();
        jCB_inquilino = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jL_garante = new javax.swing.JLabel();
        jL_inmueble = new javax.swing.JLabel();
        jCB_inmueble = new javax.swing.JComboBox<>();
        jL_propietario = new javax.swing.JLabel();
        jTF_propietario = new javax.swing.JTextField();
        jL_fechaIni = new javax.swing.JLabel();
        jDCH_fechaIni = new com.toedter.calendar.JDateChooser();
        jL_fechaFin = new javax.swing.JLabel();
        jDCH_fechaFin = new com.toedter.calendar.JDateChooser();
        jL_monto = new javax.swing.JLabel();
        jTF_PrecioAlqui = new javax.swing.JTextField();
        jB_nuevo = new javax.swing.JButton();
        jB_guardar = new javax.swing.JButton();
        jB_eliminar = new javax.swing.JButton();

        jL_tituloCalquis.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jL_tituloCalquis.setText("CONTROL DE CONTRATOS");

        jB_buscar.setText("Buscar");

        jL_codigo.setText("Código:");

        jTF_codigo_ID.setText(" ");
        jTF_codigo_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_codigo_IDActionPerformed(evt);
            }
        });

        jL_inquilino.setText("Inquilino:");

        jCB_inquilino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField1.setText(" ");

        jL_garante.setText("Garante:");

        jL_inmueble.setText("Inmueble:");

        jCB_inmueble.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jL_propietario.setText("Propietario:");

        jL_fechaIni.setText("Desde:");

        jL_fechaFin.setText("Hasta:");

        jL_monto.setText("Monto:");

        jTF_PrecioAlqui.setText(" ");

        jB_nuevo.setText("Nuevo");

        jB_guardar.setText("Guardar");

        jB_eliminar.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_inquilino)
                            .addComponent(jL_garante)
                            .addComponent(jL_codigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTF_codigo_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addGap(84, 84, 84)
                                .addComponent(jB_buscar))
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCB_inquilino, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_propietario)
                            .addComponent(jL_inmueble))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCB_inmueble, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTF_propietario)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDCH_fechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDCH_fechaIni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTF_PrecioAlqui))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB_guardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                                .addComponent(jB_eliminar)))))
                .addGap(111, 111, 111))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jL_fechaIni))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jL_fechaFin))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jL_monto))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jB_nuevo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jL_tituloCalquis, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_tituloCalquis, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_buscar)
                    .addComponent(jL_codigo)
                    .addComponent(jTF_codigo_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_inquilino)
                    .addComponent(jCB_inquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_garante))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_inmueble)
                    .addComponent(jCB_inmueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_propietario)
                    .addComponent(jTF_propietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_fechaIni)
                    .addComponent(jDCH_fechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_fechaFin)
                    .addComponent(jDCH_fechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_monto)
                    .addComponent(jTF_PrecioAlqui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_nuevo)
                    .addComponent(jB_guardar)
                    .addComponent(jB_eliminar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTF_codigo_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_codigo_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_codigo_IDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_buscar;
    private javax.swing.JButton jB_eliminar;
    private javax.swing.JButton jB_guardar;
    private javax.swing.JButton jB_nuevo;
    private javax.swing.JComboBox<String> jCB_inmueble;
    private javax.swing.JComboBox<String> jCB_inquilino;
    private com.toedter.calendar.JDateChooser jDCH_fechaFin;
    private com.toedter.calendar.JDateChooser jDCH_fechaIni;
    private javax.swing.JLabel jL_codigo;
    private javax.swing.JLabel jL_fechaFin;
    private javax.swing.JLabel jL_fechaIni;
    private javax.swing.JLabel jL_garante;
    private javax.swing.JLabel jL_inmueble;
    private javax.swing.JLabel jL_inquilino;
    private javax.swing.JLabel jL_monto;
    private javax.swing.JLabel jL_propietario;
    private javax.swing.JLabel jL_tituloCalquis;
    private javax.swing.JTextField jTF_PrecioAlqui;
    private javax.swing.JTextField jTF_codigo_ID;
    private javax.swing.JTextField jTF_propietario;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
