
package inmobiliaria_mddp.vistas;

import inmobiliaria_mddp.accesoDatos.InquilinoData;
import inmobiliaria_mddp.entidades.Inquilino;
import javax.swing.JOptionPane;





public class GestionInquilino extends javax.swing.JInternalFrame {


     
     private InquilinoData inquilino =new InquilinoData();
     private Inquilino a = null;  
    
    
    public GestionInquilino() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jB_Nuevo = new javax.swing.JButton();
        jB_Guardar = new javax.swing.JButton();
        jB_Eliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jT_idInquilino = new javax.swing.JTextField();
        jT_nombCom = new javax.swing.JTextField();
        jT_cuitInquilino = new javax.swing.JTextField();
        jT_Telefono = new javax.swing.JTextField();
        jT_LTrabajo = new javax.swing.JTextField();
        jT_NombGarante = new javax.swing.JTextField();
        jT_cuitGarante = new javax.swing.JTextField();
        jBuscar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("CONTROL DE INQUILINO");

        jB_Nuevo.setMnemonic('n');
        jB_Nuevo.setText("Nuevo");
        jB_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_NuevoActionPerformed(evt);
            }
        });

        jB_Guardar.setMnemonic('g');
        jB_Guardar.setText("Guardar");
        jB_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_GuardarActionPerformed(evt);
            }
        });

        jB_Eliminar.setMnemonic('e');
        jB_Eliminar.setText("Eliminar");

        jLabel2.setText("Id Inquilino:");
        jLabel2.setEnabled(false);

        jLabel3.setText("Nombre Completo:");

        jLabel4.setText("CUIT:");

        jLabel5.setText("Telefono:");

        jLabel6.setText("Lugar de Trabajo:");

        jLabel7.setText("Nombre Garante:");

        jLabel8.setText("CUIT Garante:");

        jT_cuitInquilino.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_cuitInquilinoFocusLost(evt);
            }
        });

        jBuscar.setText("Buscar");
        jBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jB_Nuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(jB_Guardar)
                        .addGap(96, 96, 96)
                        .addComponent(jB_Eliminar)
                        .addGap(57, 57, 57))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jT_cuitInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(133, 133, 133)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jT_nombCom)
                                        .addComponent(jT_Telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                        .addComponent(jT_LTrabajo)
                                        .addComponent(jT_NombGarante, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                        .addComponent(jT_cuitGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(34, 34, 34)
                .addComponent(jBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jT_idInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jT_idInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jT_cuitInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jT_nombCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jT_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jT_LTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jT_NombGarante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jT_cuitGarante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Nuevo)
                    .addComponent(jB_Guardar)
                    .addComponent(jB_Eliminar))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_NuevoActionPerformed
      
       limpiarCampos();
       jB_Guardar.setEnabled(true);
    }//GEN-LAST:event_jB_NuevoActionPerformed

    private void jB_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_GuardarActionPerformed
              
        
 try{
      
  
        String NomCom=(jT_nombCom.getText());
        int cuitIn=Integer.parseInt(jT_cuitInquilino.getText());
        int telContacto= Integer.parseInt(jT_Telefono.getText());
         JOptionPane.showMessageDialog(this, "Ingrese SOLO numeros enteros");
        String LugarDeTra =(jT_LTrabajo.getText());
        String NomCompletoGa =(jT_NombGarante.getText());
        int CuitGarante=Integer.parseInt(jT_cuitGarante.getText());
        
        if(a==null){
            
            a  = new Inquilino(NomCom,cuitIn,telContacto,LugarDeTra,NomCompletoGa,CuitGarante);
            
        inquilino.guardarInquilino(a);
        
        JOptionPane.showMessageDialog(null,"se guardo correctamente");
        
        }
         }catch(NumberFormatException nfe){
            
            JOptionPane.showMessageDialog(null, "error de algo");


            
        }
    


         
             
        
        
        
        
        



    }//GEN-LAST:event_jB_GuardarActionPerformed

    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarActionPerformed

         try{  
               InquilinoData inquilino =new InquilinoData();
               int cuitIn=Integer.parseInt(jT_cuitInquilino.getText());
               Inquilino a = inquilino.buscarInquilinoConCuit(cuitIn);
                                     
            
            jT_nombCom.setText(a.getNomCom());
            jT_Telefono.setText(a.getTelContacto()+"");
            jT_LTrabajo.setText(a.getLugarDeTra());
            jT_NombGarante.setText(a.getNomCompletoGa());
            jT_cuitGarante.setText(a.getCuitGarante()+"");

                        jB_Eliminar.setEnabled(true);
                        jB_Guardar.setText("Modificar");
                        jB_Guardar.setEnabled(true);
                  
                } catch ( NumberFormatException nf){
                      
                      JOptionPane.showMessageDialog(null,"sjfjggjfjjgjjfjfgITO");
           
                    
                }





        // TODO add your handling code here:
    }//GEN-LAST:event_jBuscarActionPerformed

    private void jT_cuitInquilinoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_cuitInquilinoFocusLost
     if (jT_cuitInquilino==null || jT_cuitInquilino.getText().equalsIgnoreCase("")){
         JOptionPane.showMessageDialog(this, "Ingrese numeros enteros");
     }
    }//GEN-LAST:event_jT_cuitInquilinoFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Eliminar;
    private javax.swing.JButton jB_Guardar;
    private javax.swing.JButton jB_Nuevo;
    private javax.swing.JButton jBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jT_LTrabajo;
    private javax.swing.JTextField jT_NombGarante;
    private javax.swing.JTextField jT_Telefono;
    private javax.swing.JTextField jT_cuitGarante;
    private javax.swing.JTextField jT_cuitInquilino;
    private javax.swing.JTextField jT_idInquilino;
    private javax.swing.JTextField jT_nombCom;
    // End of variables declaration//GEN-END:variables





private void limpiarCampos (){
   jT_idInquilino.setText("");
   jT_nombCom.setText("");
   jT_cuitInquilino.setText("");
   jT_LTrabajo.setText("");
   jT_NombGarante.setText("");
   jT_cuitGarante.setText("");
   jT_Telefono.setText("");
   jB_Guardar.setEnabled(false);
   jB_Eliminar.setEnabled(false); 
}
}